### ISSUE TITLE
Suggestions to improve vue-toastification

### ISSUE THREAD

**Issue by connecteev** [Maronato/vue-toastification#1]
Amazing plugin. Some suggestions for you:
1. Option to show the close button only on hover, exactly like reddit! See https://prnt.sc/plklrn
2. Add actions like https://github.com/shakee93/vue-toasted
3. Add options for enter and leave transitions to https://maronato.github.io/vue-toastification/ with ability to select both and mix-and-match. 
4. Add options to add icon to https://maronato.github.io/vue-toastification/ (I know it can be customized, but making it even easier to use) like https://github.com/shakee93/vue-toasted and reddit
5. Add full-screen option like https://github.com/shakee93/vue-toasted

**Comment by Maronato** [comment]
Hey @connecteev! Thanks for the first issue :)
About your suggestions:

1. I do like the idea of hiding the close button on hover! I'll make sure to add that to the next release.
2. You can add actions with custom components. Wouldn't adding actions on top of that be a little redundant?
3. Do you mean adding the option to set just enter/leave transitions? Because you can already set transitions with the `transition` option. I do think that setting individual transitions would be helpful though, and would require very small changes. I'll add that to the next release as well.
4. Looking at vue-toasted's code I see that all they do when you select an icon pack and set the icon is prepend a `fa fa-` or `mdi` to the icon name you provide. While I do see how it would make it a little easier to use, I feel like it would add too little functionality to justify the increase in bundle size.
5. Are full-screen toasts a thing? I thought the idea of toasts was to be as unobtrusive as possible. If one wants to fill the entire screen with a message then probably a toast is not the right component.

**Comment by connecteev** [comment]
Hey @Maronato! I love this package and will definitely plan to use it. Thanks for also being receptive to feedback and ideas to improve it more. My comments below!

> I do like the idea of hiding the close button on hover! I'll make sure to add that to the next release.
This would be really cool, esp if you can make it exactly like Reddit's! Just log in and you will see it.

> You can add actions with custom components. Wouldn't adding actions on top of that be a little redundant?
Yes, that's a good point. I was thinking this would be a "quick" way for people that dont want to create components. Please ignore if it's going to significantly increase bundle size though.

> Do you mean adding the option to set just enter/leave transitions? Because you can already set transitions with the transition option. I do think that setting individual transitions would be helpful though, and would require very small changes. I'll add that to the next release as well.
Perfect - would love to be able to control individual transitions for enter and leave. TO be honest I have yet to try this out. I will be doing that in the coming days and report back. When do you expect the next release? No pressure or rush, just asking if I should wait :)

> Looking at vue-toasted's code I see that all they do when you select an icon pack and set the icon is prepend a fa fa- or mdi to the icon name you provide. While I do see how it would make it a little easier to use, I feel like it would add too little functionality to justify the increase in bundle size.
Definitely understand how bundle size is a concern. If this is already possible (and it might be), an example using [the full API ](https://github.com/Maronato/vue-toastification#api) on the demo page would be helpful to people new to the plugin. This will demonstrate it's power (icons, transitions, and the dozen other options you have already!)

> Are full-screen toasts a thing? I thought the idea of toasts was to be as unobtrusive as possible. If one wants to fill the entire screen with a message then probably a toast is not the right component.
Good point! One additional thought here, is it feasible at all to combine toast with popup / modal functionality? That way, people don't have to install 2 plugins. I've always wondered why people treat them as separate when they can be the same. 
I know it does open up a small can-o-worms (modal height/width, positioning, background masks, close button customization, modal open and close triggers, modal enter/leave transitions, modal chaining, etc) but I think the code for toasts and popups/modals would be 90% the same. I don't know how complex all of this would be - but just putting it out there! Then again, all of this may be imported as an option, with both the toast and modal using the same underlying core. Defer to your best judgement on this one.

Thanks again for the responsiveness and this plugin, look forward to seeing it progress and improve!

**Comment by Maronato** [comment]
I've taken a few of your suggestions and released them as the [0.2.0](https://github.com/Maronato/vue-toastification/releases/tag/v0.2.0) version that is available now.

I haven't implemented the close-button-hover-thingy yet because I haven't decided on how it'll interfere with other parts of the toast. Shouldn't take long though.

> One additional thought here, is it feasible at all to combine toast with popup / modal functionality? That way, people don't have to install 2 plugins. I've always wondered why people treat them as separate when they can be the same.

Modals are a whole different beast that would probably share little code with the current implementation, IMO. Besides that, most UI frameworks like [Vuetify](https://vuetifyjs.com/en/components/dialogs) already implement modals but usually don't implement toasts (thats why this plugin was born).

I do see your point, though and I'd be willing to try and create _another_ plugin with modals that follow a similar design pattern to the toasts. Adding modals here would bloat the plugin with stuff that not everybody may find useful :/

**Comment by connecteev** [comment]
@Maronato that's amazing.. I installed and tried out the latest code. Going to incorporate it into my nuxt.js project later this week.

Agree on keeping modals separate - just thought I'd send the ideas to you, because you never know - I was unsure how easy it would be and how much code would get reused in implementing them. Another plugin for that would be awesome as well.

Sending a few more ideas to build on our discussion (in addition to the ones above like the close button on hover)

To add to the [transitions](https://github.com/Maronato/vue-toastification#transition-classes):
- click "simple" button [here](http://vue-js-modal.yev.io/) (fade in / slide down to appear and fade out / slide up to disappear) - I would want to use this for top-centered toasts
- click "demo login" button [here](http://vue-js-modal.yev.io/) (fade in / slide up to appear and fade out /slide down to disappear) - I would want to use this for bottom-centered toasts
- Similarly for slide left / right - see more examples [here](https://chenjiahan.github.io/vodal/)
(I dont like rotate, door, flip..they are cheesy)
- More fun transitions [here](https://tympanus.net/Development/ModalWindowEffects/), especially for when you do implement modals

Allow customizing the background color and text color (so there's adequate contrast) on the [demo page](https://maronato.github.io/vue-toastification/) post-install.

Your responsiveness makes it very likely that I'll be using this package. Look forward to seeing this improve and become more amazing than it is.

**Comment by Maronato** [comment]
Hey @connecteev! More built-in transitions is another thing I'm looking into adding soon. Please take a look at [animate.css](https://daneden.github.io/animate.css/) transitions. They are pretty light and good contenders for future releases.

Also, if you'd like to help, feel free to create a PR adding new transitions. Use [_bounce.css](https://github.com/Maronato/vue-toastification/blob/master/src/scss/animations/_bounce.scss) as an example.

On customizing the BG on the demo page, I fear that by adding that many options it'll make it a little hard to use and sort the information, especially because I'd need to add code snippets for the style files, which can get pretty big.

> so there's adequate contrast

I'd love color scheme suggestions, as I'm a little colorblind and my notion of good contrast may not reflect the general opinion.
New options may be implemented as extra themes, as I'm looking into implementing a theming system.

**Comment by ndragun92** [comment]
Animista is good as well: http://animista.net/
Keep up the good work!

**Comment by connecteev** [comment]
Thanks @ndragun92 animista looks good too.
@Maronato Just sent in a PR for 2 transition options.

For color generators check out:
- https://paletton.com/
- http://colorsafe.co/
But I would give the user the ability to customize the background and text colors themselves.

**Comment by Maronato** [comment]
Maybe I misinterpreted, but users can already customize background and text colors themselves by [changing scss variables](https://github.com/Maronato/vue-toastification/blob/master/src/scss/_variables.scss). Did you mean that or specifically on the demo page?

Also, I've changed this issue to a discussion issue and I'll open a new one focused on the hiding close buttons on hover feature request

**Comment by connecteev** [comment]
@Maronato great, sounds good, I think the hover feature request will add some nice visual polish...cant wait to see it.
Hope the PR was useful, I made the changes you wanted to it.
Re: colors, I meant pulling them front-and-center into the [demo page](https://maronato.github.io/vue-toastification/) - most devs are going to have their own theme and will want an easy way to change the colors, which is why imo this customization will be welcomed. The theme idea is good too, to have predefined presets, but this will give them full control.

**Comment by connecteev** [comment]
FYI: this plugin does both modals and toasts...you dont have to combine them into 1 library but sending this to you for reference only
https://terryz.github.io/vue/#/dialog/demo

**Comment by connecteev** [comment]
ping! to keep this open

**Comment by Maronato** [comment]
Am working on the discussed features and should release them shortly after the holidays

**Comment by GTCrais** [comment]
Another suggestion - allow Vue components to be passed for icons (left 'info' etc. icon, and the right 'close' icon).

1) Info icon:
While it's currently possible to modify it, I don't think it's flexible enough. For example I use Vue Material Icons, so I import each icon that I use as a Vue component. It's impossible to use this component for the info icon. I don't want to use the entire Material icon set just so I can display a couple of them in my toasts.

2) Close icon:
From what I see, it's impossible to customize this icon?

Current solution: hide both left icon and close icon, and use custom Vue component as toast content to display both toast text, and the two icons.

Apart from this, love the package, great job!

**Comment by Maronato** [comment]
@GTCrais thanks for the suggestions!

Both have been added in [v0.8.0](https://github.com/Maronato/vue-toastification/releases/tag/v0.8.0). Please give it a try and report any bugs you find :)
