### ISSUE TITLE
"container" option for this.$toast()?

### ISSUE THREAD

**Issue by guanzo** [Maronato/vue-toastification#103]
I'd like to display toasts in multiple areas of my app.

## Detailed Description
Here's my app layout

![](https://i.gyazo.com/153774a25a4a2dee1b9431e8c178f203.png)

The black rectangles are my potential toast containers.
The red rectangles are the toasts.

When i call `this.$toast()`, i'd like to specify which container to append them to.

## Context
This option will make the lib more flexible.  It'll allow the user to place toasts literally anywhere they want.

I read something about "updateDefaults", but that doesn't really fit my use case, as I could potentially have 2 toasts display at the same time, in different areas. I mean i could technically hack my way with regards to timing issues, but it's not elegant imo.

**Comment by Maronato** [comment]
Hello!

The `this.$toast` object is what I call a "toast interface". You may create as many interfaces as you want and each may create a new container or attach to one and emit events to it. [Learn more.](https://github.com/Maronato/vue-toastification#generic-registration)

By design, each interface must be independent of others, since they may be created dynamically and whatnot. Because of this, there is no simple way to add a "container" option to the interface since that would mean keeping track of a list of mounted containers and interfaces.

That said, what you want can be easily achieved with a custom vue plugin:
```js
// toast-plugin.js
import { createToastInterface } from "vue-toastification";
import "vue-toastification/dist/index.css";

const installPlugin = (Vue) => {
  // Create the first interface
  const toastOneOptions = {};
  const toastOne = createToastInterface(toastOneOptions);

  // Create the second interface
  const toastTwoOptions = {};
  const toastTwo = createToastInterface(toastTwoOptions);
  
  // Register them as this.$toastOne and this.$toastTwo
  Vue.$toastOne = toastOne;
  Vue.prototype.$toastOne = toastOne;
  Vue.$toastTwo = toastTwo;
  Vue.prototype.$toastTwo = toastTwo;
};

export default installPlugin
```
Register it normally:
```js
// main.js
import Vue from "vue";
import Toast from "./toast-plugin.js";

Vue.use(Toast);
```

And then use it with `this.$toastOne` and `this.$toastTwo`.


Here is a [demo codesandbox](https://codesandbox.io/s/elastic-moon-vgbmn?file=/src/App.vue) that registers them a little differently but leverages the same concept.

**Comment by guanzo** [comment]
Perfect, this looks good to me. Thanks!
