### ISSUE TITLE
Is there a way to make the toast function globally available?

### ISSUE THREAD

**Issue by stylefieber** [Maronato/vue-toastification#134]
I liked the approach where I could prototype some important and often used functions or plugins by doing

`Vue.prototype.$toast = toast`

While we can do this now via 
`app.config.globalProperties.$toast = toast` <= this doesn't work.

I'm wondering how this gonna work with Vue 3 version of toastification. 

Any hint?

**Comment by Maronato** [comment]
Hello!

Firstly, I don't know if you noticed, but there is already a [Vue 3-compatible Vue Toastification](https://github.com/Maronato/vue-toastification/tree/next) under the tag `next`.

For Vue 3, most plugins are switching to [dependency injection](https://v3.vuejs.org/guide/component-provide-inject.html) because it plays nicely with hooks. Vue Toastification is no different, and v2 offers a built-in hook [`useToast`](https://github.com/Maronato/vue-toastification/tree/next#creating-toasts) for easy access to the injected interface from within `setup()`.

That said, it is still possible to bind `this.$toast` using a global [`EventBus`](https://github.com/Maronato/vue-toastification/tree/next#creating-toasts) and creating a new plugin function that binds `this.$toast`.

Here is a working demo that shows how you can do that. Later on, this might also become the recommended way to access the `toast` interface inside Vuex actions/mutations.

[![Edit Global Vue toastification toasts](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/global-vue-toastification-toasts-kl7bw?fontsize=14&hidenavigation=1&theme=dark)

For posterity, here are the relevant code snippets:

```ts
// toast.ts
import { App } from 'vue';
import {
  createToastInterface,
  EventBus,
  PluginOptions,
  toastInjectionKey
} from 'vue-toastification';

// This will be the global event bus
const globalEventBus = new EventBus();

// Call this function once to create and mount a global toast container
export function createGlobalToast(options?: PluginOptions) {
  return createToastInterface({ ...options, eventBus: globalEventBus });
}

// Returns an interface to the global toast container
export function useGlobalToast() {
  return createToastInterface(globalEventBus);
}

// Use this as a plugin to register instance and injected toasts
export function provideAppToast(app: App, options?: PluginOptions) {
  // Create the global container
  const toast = createGlobalToast(options);

  // Provide using Vue dependency injection
  app.provide(toastInjectionKey, toast);

  // Bind to the global object so it can be called with this.$toast
  app.config.globalProperties.$toast = toast;
}
```

Install as a plugin:
```ts
// main.ts
import { createApp } from 'vue';
import { provideAppToast } from './toast';
// ...

app.use(provideAppToast)
```

Use it:
```ts
import { useToast } from "vue-toastification";
import { useGlobalToast } from "./toast"

// Option 1: Get an interface to the global toast container directly
// May be called anywhere, even inside vuex and is SSR-tolerant (will trigger warnings but won't break)
const globalToast = useGlobalToast()

export default defineComponent({
  name: "App",
  setup() {

    // Option 2 (preferred): Inject the app-provided toast interface and return it from setup
    const setupToast = useToast()
    return { setupToast }
  },
  methods: {
    showGlobalToast() {
      // Option 1 usage
      globalToast.success("Global toast!");
    },
    showSetupToast() {
      // Option 2 usage
      this.setupToast.error("Setup toast!");
    },
    showPrototypeToast() {
      // Option 3 (app.config.globalProperties) usage
      this.$toast.info("Prototype toast!");
    }
  }
});
```

If you feel like this response does not answer your question, feel free to reopen the issue :)

**Comment by stylefieber** [comment]
Thank you - that does the trick!
