### ISSUE TITLE
v2.0.0-beta.5 Toast not dismissing after timeout

### ISSUE THREAD

**Issue by J-T-McC** [Maronato/vue-toastification#137]
## Versions
v2.0.0-beta.5

## Describe the bug
Toast is not dismissed after the timeout expires even though the timeoutHandler test is passing. Changing the event listeners to camel case in VtToast.vue makes the dismiss work but the timeoutHandler test no longer passes while "emits close-toast on animationend" does. Changing the event to single word (i.e. 'dismiss') throughout and all tests + timeout dismiss works

## Expected behavior
Toast dismissed after timeout expires

## Steps to reproduce
add v2.0.0-beta.5 package

Reproduction: [demo](https://codesandbox.io/s/vue3-forked-7te8o?file=/src/components/HelloWorld.vue).

Steps:
1. Install v2.0.0-beta.5
2. Set up plugin
3. Toggle toast

## Your Environment
VueJS 3.0.1

Latest Chrome

**Comment by restyler** [comment]
I can confirm the bug on vue@3.0.2 + vue-toastification@2.0.0-beta.5

**Comment by emresudo** [comment]
I can confirm the bug on vue@3.0.0 + vue-toastification@2.0.0-beta.5

**Comment by Maronato** [comment]
Hello!
Thank you for reporting this and for your analysis. 

I've done some digging and found that the issue seems to come from [this commit](https://github.com/vuejs/vue-next/commit/62f26173ba715fd8bf2b131e19d94275106e830d) on `vue-next`. What it does is change how the event listener name is normalized.

[Here is an example](https://5f7cecbc6bc56900079a0a68--vue-next-template-explorer.netlify.app/#%7B%22src%22%3A%22%3Cdiv%20%40close-toast%3D%5C%22doStuff%5C%22%3EHello%20World!%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22mode%22%3A%22module%22%2C%22prefixIdentifiers%22%3Afalse%2C%22optimizeImports%22%3Afalse%2C%22hoistStatic%22%3Afalse%2C%22cacheHandlers%22%3Afalse%2C%22scopeId%22%3Anull%2C%22ssrCssVars%22%3A%22%7B%20color%20%7D%22%2C%22bindingMetadata%22%3A%7B%22TestComponent%22%3A%22setup%22%2C%22foo%22%3A%22setup%22%2C%22bar%22%3A%22props%22%7D%7D%7D) from the Template Explorer showing how, before the change, the following template
```vue
<div @close-toast="doStuff">Hello World!</div>
```

Would get compiled to:
```js
export function render(_ctx, _cache, $props, $setup, $data, $options) {
  return (_openBlock(), _createBlock("div", { "onClose-toast": _ctx.doStuff }, "Hello World!", 40 /* PROPS, HYDRATE_EVENTS */, ["onClose-toast"]))
}
```

In fact, Vue-Toastification's `v2.0.0-beta.5` distribution code looks like:
```js
typeof _ctx.content === 'string')
        ? (openBlock(), createBlock(Fragment, { key: 0 }, [
            createTextVNode(toDisplayString(_ctx.content), 1 /* TEXT */)
          ], 64 /* STABLE_FRAGMENT */))
        : (openBlock(), createBlock(resolveDynamicComponent(_ctx.getVueComponentFromObj(_ctx.content)), mergeProps({
            key: 1,
            "toast-id": _ctx.id
          }, _ctx.content.props, toHandlers(_ctx.content.listeners), { "onClose-toast": _ctx.closeToast }), null, 16 /* FULL_PROPS */, ["toast-id", "onClose-toast"]))
    ], 10 /* CLASS, PROPS */, ["role"]),
```

After the change, however, a handler for `close-toast` gets compiled to `onCloseToast`, as you can see it in this [other example](https://5f7d2f325b5cf30008c767a9--vue-next-template-explorer.netlify.app/#%7B%22src%22%3A%22%3Cdiv%20%40close-toast%3D%5C%22doStuff%5C%22%3EHello%20World!%3C%2Fdiv%3E%22%2C%22options%22%3A%7B%22mode%22%3A%22module%22%2C%22prefixIdentifiers%22%3Afalse%2C%22optimizeImports%22%3Afalse%2C%22hoistStatic%22%3Afalse%2C%22cacheHandlers%22%3Afalse%2C%22scopeId%22%3Anull%2C%22ssrCssVars%22%3A%22%7B%20color%20%7D%22%2C%22bindingMetadata%22%3A%7B%22TestComponent%22%3A%22setup%22%2C%22foo%22%3A%22setup%22%2C%22bar%22%3A%22props%22%7D%7D%7D) from the Template Explorer.

The same template as above now gets compiled to:
```js
export function render(_ctx, _cache, $props, $setup, $data, $options) {
  return (_openBlock(), _createBlock("div", { onCloseToast: _ctx.doStuff }, "Hello World!", 40 /* PROPS, HYDRATE_EVENTS */, ["onCloseToast"]))
}
```

The fix, then, should be as simple as recompiling the library using the newest version of `compiler-dom`. My local tests show that once recompiled, the issues are gone.

I'll create a PR and push these changes into the next release, so please give it a try.

**Comment by Maronato** [comment]
@J-T-McC The issue seems to be fixed now. Please try it out :)

[![Edit vue3 (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue3-forked-lznyp?fontsize=14&hidenavigation=1&theme=dark)

**Comment by J-T-McC** [comment]
Thanks @Maronato, all good now.
