### ISSUE TITLE
 Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by dilotec-2015** [Maronato/vue-toastification#147]
Hi,

my vue project is coded with TypeScript.
Whren i use your toast implementation i get this error in the console:

rc2Contentscript.js:544 Uncaught TypeError: Cannot read property 'appendChild' of null
    at rc2Contentscript.js:544
(anonymous) @ rc2Contentscript.js:544

can you imagine how to work arround this error?

regards waldemar

**Comment by Maronato** [comment]
Hello! Thank you for reporting :)

When filling out bug reports, please stick to the [issue template](https://github.com/Maronato/vue-toastification/issues/new?assignees=&labels=Type%3A+Bug%2C+Status%3A+Available&template=bug_report.md&title=).

This error does not seem to be caused by Vue Toastification, or at least not directly.

Please create another issue following the [issue template](https://github.com/Maronato/vue-toastification/issues/new?assignees=&labels=Type%3A+Bug%2C+Status%3A+Available&template=bug_report.md&title=) so that I know how to reproduce it.
