### ISSUE TITLE
Cannot find module 'vue-toastification' or its corresponding type declarations error raise in vue3 ts

### ISSUE THREAD

**Issue by tonytony2020** [Maronato/vue-toastification#246]
## Versions

- 2.0

## Describe the bug

Cannot find module 'vue-toastification' or its corresponding type declarations error raise in vue3 ts.

my package.json settings
```
    "vue": "^3.0.0",
    "vue-class-component": "^8.0.0-0",
    "vue-toastification": "^2.0.0-rc.1",
```

## Expected behavior

Instead of breaking the page, it should run and up.

## Steps to reproduce

Reproduction 
Steps:
1. Install normally,  create a new project with vue3 with ts support
2. Set up plugin,  `yarn add vue-toastification@next`

## Your Environment

 - OS: macOs latest ver
 - Browser chrome
 - Version latest ver

**Comment by marlonlewis2020** [comment]
I had a similar issue. I found two solutions to fixing it.

**Solution 1.**
from [stackoverflow.com](https://stackoverflow.com/questions/74667905/how-to-use-vue-toastification)
After re-confirming I had the nuxt and vue-toastification modules installed in my node_modules folder,
1. I created a plugis folder in my root directory (I did not already have one).
2. I created a file called "vue-toastification.client.js"
3. I copied the following code as the only content in that file:
  ```
  import { defineNuxtPlugin } from '#app'
  import Toast from 'vue-toastification'
  import 'vue-toastification/dist/index.css' // if needed
  
  export default defineNuxtPlugin((nuxtApp) => {
      nuxtApp.vueApp.use(Toast)
  }) 
```
4. I saved it and the issue was resolved

**Solution 2.**
from [askjavascript.com](https://askjavascript.com/cannot-find-module-and-its-corresponding-type-declarations/#:~:text=To%20fix%20the%20%E2%80%9Ccannot%20find%20module%20and%20its,import%20the%20library%20in%20your%20program%20or%20file.)
After re-confirming I had the nuxt and vue-toastification modules installed in my node_modules folder,
1. I create a decs.d.ts file in the root folder of the project
2. I copy the following code as the only content in that file:
  `declare module 'vue-toastification'`
3. I saved it and the issue was resolved
