### ISSUE TITLE
Safari toastr stretched

### ISSUE THREAD

**Issue by Cannonb4ll** [Maronato/vue-toastification#27]
Hello!

In safari the Toastr is stretched, I have used multiple CSS solutions (using dist css, scss, etc) but none resolve this. I have done no custom CSS or anything else to modify.

**Safari:**
![img](https://dsc.cloud/a00d3a/Screen-Shot-2019-12-19-22-21-52.93.png)

**Chrome:**

![img](https://dsc.cloud/a00d3a/Screen-Shot-2019-12-19-22-21-26.56.png)

**Comment by Cannonb4ll** [comment]
Update: Seems to have to do with the SVG icons, if I remove SVG toast remains normal size.

**Comment by Maronato** [comment]
Hey @Cannonb4ll !

Thank you for reporting this. You are indeed correct, the issue seems to be somewhat [known](https://stackoverflow.com/questions/26091989/svg-viewbox-height-issue-on-ios-safari) to happen when using Safari.

I've released a fix for it (along with a couple of other things) in [v0.6.5](https://github.com/Maronato/vue-toastification/releases/tag/v0.6.5). Please try it out and reopen the issue if the problem persists.
