### ISSUE TITLE
Not sure how to use filterBeforeCreate with Composition API

### ISSUE THREAD

**Issue by sundayz** [Maronato/vue-toastification#291]
Hi, thanks for the great work on this library! I'm trying to use vue-toastification with Nuxt and the composition API, but the only example of how to do it that I could find was in #268, but this example says to use the `useToast` composable inside the hook, and I don't understand how this works.

I'm using v1.7.11 of the package right now which had some issues with the composition API so I'm setting up the toast interface in a Nuxt plugin like this:

```ts
export default () => {
    onGlobalSetup(() => {
        provideToast({
            // other options here ...
            filterBeforeCreate: (toast, toasts) => {
                const $toast = useToast();
                console.log($toast); // undefined
                return toast;
            }
        });
    });
};
```

I'm not sure how to access the toast interface inside the hook so I can clear the notifications. I want only one notification to be visible at all times, and new notifications should instantly replace old ones.

**Comment by Maronato** [comment]
Hello!

Yes, you won't be able to do the same thing because the example you mentioned is for version 2 of the plug-in. 

For version 1, `useToast` only works from within a setup function. By the time the `filterBeforeCreate` hook is called, the setup context is no longer available.
What you can do, though, is to call `useToast` inside the setup context and pass the reference to the `filterBeforeCreate` closure:

```ts
export default () => {
    onGlobalSetup(() => {
        let $toast;
        provideToast({
            // other options here ...
            filterBeforeCreate: (toast, toasts) => {
                // $toast should be defined here
                console.log($toast);
                return toast;
            }
        });
        // Only call useToast after providing it
        $toast = useToast();
    });
};
```

I haven't tested the code above, but it should work.

Also, if you wish to call `provideToast`, make sure that you are *not* using the built-in nuxt module. Those are not compatible in the version you are using, and you should use either one or the other.

**Comment by sundayz** [comment]
Thanks a lot for the help! Works great. I will update later to the newer version later where the built-in nuxt module works, How do you use `filterBeforeCreate` when configuring the plugin in the `nuxt.config.js` file though? Doesn't seem like a good idea to be writing code in the config file like that.

**Comment by Maronato** [comment]
Yeah, you probably can't do the same thing from within the config file.
Instead you should call [`.updateDefaults`](https://github.com/Maronato/vue-toastification#updating-default-options) from `onGlobalSetup` to configure `filterBeforeCreate`, similarly to what was done above

**Comment by sundayz** [comment]
Nice! Thanks
