### ISSUE TITLE
Pass icon type to icon component

### ISSUE THREAD

**Issue by rchl** [Maronato/vue-toastification#76]
Would it make sense to pass the `type` prop onto the custom component here:
https://github.com/Maronato/vue-toastification/blob/514e84794dc09bba9b880b4f22b5b902c927ed9d/src/components/VtIcon.vue#L2
so that it could set custom styling based on that?

Currently, we can do that based on classes set on parent components but it's not as clean (wouldn't easily let me use same component for vue-toastification and other code).

Setting a prop that custom component doesn't handle is fine, I believe. There should be no error. The only issue would be if that component already handles prop with the same name but that is unlikely I guess.

**Comment by Maronato** [comment]
It does not seem to be a breaking change because custom icon components would not receive any props from Vue Toastification, but it diverges a bit from the current API.
If `type` is passed to the icon, users would likely expect `type` to also be passed to close buttons, toast components, etc.

Close buttons are, again, fine, but toast components allow users to pass custom `props` and those may already include `type`. In that case, I do not know which prop would take precedence, so that may be breaking.

Can you elaborate a little more on your use case?

A possible current solution is to use [type defaults](https://github.com/Maronato/vue-toastification#presetting-default-toast-options-per-type). They allow you to define default parameters per toast type, so you can set default icons for each type.

```js
Vue.use(Toast, {
  toastDefaults: {
    "success": {
      icon: MyCustomSuccessIcon
    }
  }
}
```

Here is an example that sets custom JSX icons for each toast type, passing the `type` prop, and possibly others, automatically:

[![Edit objective-swirles-2sxes](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-swirles-2sxes?fontsize=14&hidenavigation=1&theme=dark)

If the proposed solution does not satisfy your needs we can discuss further.

**Comment by rchl** [comment]
I'll try that out, thank you.
I don't use JSX so need to figure out how to do it using render function I guess (or of course create small wrapper components).

**Comment by Maronato** [comment]
All you should need is, instead of:
```js
const renderIcon = type => ({
  render: h => <CustomIconComponent type={type} />
});
```
do:
```js
const renderIcon = type => ({
  render: createElement => createElement(CustomIconComponent, { props: { type } })
});
```

**Comment by rchl** [comment]
Thank you.
Btw, since you've asked, my use case is being able to reuse same custom components for vue-toastification and for identically looking but inline notifications (shown within the content).

**Comment by rchl** [comment]
The solution works for me. Thank you very much for your support. :)
