### ISSUE TITLE
Allow setting position offset in options

### ISSUE THREAD

**Issue by Pyro979** [Maronato/vue-toastification#81]
Right off the bat, I just wanna say, beautiful library =c)

I'd love to be able to overwrite the position offset.

## Detailed Description

Right now we can set the position based on position names (top-right, top-center, etc). This is great for most use cases. I think it'd be helpful to be able to also set the position using an offset based on whatever units are appropriate. This is potentially made more difficult since the positioning seems to be responsive based on a 600px breakpoint, but there could be 2 options (position_offset, position_offset_sm).

## Context

I have a floating header in my app, and I'd like to have the toast show up top_center, but below the header. The header height can change dynamically, but since the options of toasts can be changed dynamically, I can watch for that and adjust.

I would think there could be other folks that have elements they don't want to be covered by the toasts.

## Possible Implementation

The options could possibly look like this: 
`{position:{position:"top-center", "top":"150px"}}`
`{position:{position:"bottom-right", "bottom":"3em", "right":"1em"}}`

The code would then set the **margin** of the container to add additional offset(s). It should probably also be able to take these in as global defaults, similarly to how you can configure defaults by error type.

Of course a work around can be overwriting the css files, but that's not a great experience, and would be difficult to do dynamically.

Thanks again for a great library.

**Comment by Maronato** [comment]
Hello! Glad you like it :)

I understand the problem, but I don't think the proposed solution would work.

I'm assuming the `{position:{position:"top-center", "top":"150px"}` would be set when calling the toasts as in:
```js
this.$toast("content", {
  position: {
    position: "top-center",
    "top": "150px"
  }
})
```

This would only set the margin of this single toast relative to other toasts. If you only had one toast per container, it would look like this:
<img width="772" alt="CleanShot 2020-05-07 at 18 51 35@2x" src="https://user-images.githubusercontent.com/19658460/81348112-dc5e9600-9093-11ea-99e6-3801efa273b8.png">

But once you had multiple toasts per container, it could would look like this:
<img width="397" alt="CleanShot 2020-05-07 at 18 54 57@2x" src="https://user-images.githubusercontent.com/19658460/81348335-4414e100-9094-11ea-899f-3d417158237f.png">

And you can see that the margins are only relative to the element above. This can already be done pretty easily and dynamically using custom CSS classes:
```js
this.$toast.success("With margin!", {
  toastClassName: "my-custom-toast-class"
});
```
```css
.Vue-Toastification__toast.my-custom-toast-class {
  margin-top: 50px !important;
}
```

**Now assuming you want is to offset just the first toast of the stack** all of the following toasts behave normally, like this:
<img width="699" alt="CleanShot 2020-05-07 at 20 00 01@2x" src="https://user-images.githubusercontent.com/19658460/81352623-652dff80-909d-11ea-86d2-9ef469695806.png">


Then the option to change the offset must not be on the toasts themselves, but on the container during plugin creation.
It can't be on the toast because that will lead to confusing behavior. For example, what would the offset be for the following toasts?
```ts
this.$toast.success("first" { position: "top-right" })
this.$toast.success("second" { position: { position: "top-right", top: "30px" }})
this.$toast.success("third" { position: { position: "top-right", top: "50px" }})
```

The first toast would start with no margin, then, when the second one appeared, both would jump to 30px and then to 50px when the last one showed up. This is confusing because we declared the **toast** to have the margin, but the change happened to the container.

Therefore, this option cannot live on the toast, but on the plugin initialization and must be changed using `this.$toast.updateDefaults()`

Which can be easily and dynamically achieved using CSS classes:
```ts
// Set container class
this.$toast.updateDefaults({ containerClassName: "custom-class" })
this.$toast.success("I'm a toast")
// Unset it
this.$toast.updateDefaults({ containerClassName: "" })
```
```css
.Vue-Toastification__container.top-right.custom-class {
  top: 50px;
}
```

Let me know if my reasoning was clear and if this solution works for you.

> Note: There is currently a [bug](#84) that prevents updating `containerClassName` using `.updateDefaults()`, but I've found a fix and will release it today.

**Comment by Pyro979** [comment]
@Maronato thank you for a quick reply. Yes, you're right, the solution would definitely have to be based on the container. I think for a lot of cases where the offset is static, it would work great, but my use case has a dynamic offset. That being said I found this [article](https://www.telerik.com/blogs/passing-variables-to-css-on-a-vue-component) that has some promise of solving this issue w/out introducing the feature into your library (though I wouldn't say no if you decided to still add it). 

I'll update this issue if I can get it to work.

**Comment by Pyro979** [comment]
For posterity, here is how I solved it for now (again @Maronato if you decide to add it as a feature let me know 😄 )

In the function that knows the header height was updated:
```
//get header DOM element
let header = document.getElementById("header_hidden_false");
 //Get header height. Feel free to set your own min-height.
let headerHeight = header == null ? 135 : header.offsetHeight;
//this sets a a css variable into :root context
document.documentElement.style.setProperty("--toast-top-offset",toastTopOffset + "px");
```
In my App.vue I added this style. In my case it was global, but you can do it based on custom classes as described by @Maronato above.
```
.Vue-Toastification__container.top-center {
  margin-top: var(--toast-top-offset);
}
```

References:
https://www.telerik.com/blogs/passing-variables-to-css-on-a-vue-component
https://css-tricks.com/updating-a-css-variable-with-javascript/
https://plainjs.com/javascript/styles/getting-width-and-height-of-an-element-23/

**Comment by Pyro979** [comment]
Feel free to close if this is unlikely to become a feature.

**Comment by Maronato** [comment]
My reason for not implementing this right now is that I wanted to avoid making style modifications directly through JS as they are harder to track down and debug by the end-user. I also fear that if I implement this feature it'll serve as a pretext for other people's dynamic styling requests, to which I'll have a hard time saying no.

I'll, however, leave it open for a while as a discussion and if more people show interest I'll reconsider implementing it.

**Comment by Pyro979** [comment]
Note for anyone trying to implement my solution with injecting CSS variable, this works on modern browsers only (and not for IE11 for example). Something to be aware of if legacy browser support is important to you.

**Comment by Maronato** [comment]
Vue Toastification does not work on IE11 by default anyway because it uses `Object.assign`, `Object.values` and `TouchEvent`

**Comment by Pyro979** [comment]
I was using polyfills to have my app work in IE11, which was working at some point. That being said, I just went to go check, and it's completely borked on IE11, and I'm not sure I'll be able to fix it. SO the point is moot. CSS variable is probably the best way to customize this library for something this dynamic.

Thanks @Maronato
